Bp 5984/add list component
Clustaar/webchat-components pull request #35
Opened 2022-07-01 08:13 UTC by Yosekai

2022-07-19 09:07 UTC, szine commented on angular.json
> +              "src/custom-theme.scss",
On évite l'utilisation de plusieurs fichier, ca augmente les couts.

2022-07-19 09:08 UTC, szine commented on package.json
> +    "@angular/cdk": "^11.2.13",
Enlelver le ^

2022-07-19 09:11 UTC, szine commented on src/styles.css
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
C'est pas notre font ?

2022-07-19 12:56 UTC, Yosekai commented on src/app/demo/actions.ts
> +            { type: 'choice', title: 'zajeihgu', imageUrl: 'https://via.placeholder.com/25' },
Fait

2022-07-25 08:06 UTC, szine commented on package.json
> +    "source-map-explorer": "^2.5.2",
Enlever "source-map-explorer": "^2.5.2"", des dependencies.

2022-07-25 08:08 UTC, szine commented on projects/clustaar-webchat-components/src/lib/switch/switch.html
> +    <list-action [list]="action.list" (onChoiceSelected)="choiceSelected($event)" (onLoadNextAction)="loadNextAction()"></list-action>
Il faut passer l'action, et pas le action.list

2022-07-25 08:53 UTC, Yosekai commented on package.json
> +    "source-map-explorer": "^2.5.2",
Fait

2022-07-25 08:56 UTC, Yosekai commented on projects/clustaar-webchat-components/src/lib/switch/switch.html
> +    <list-action [list]="action.list" (onChoiceSelected)="choiceSelected($event)" (onLoadNextAction)="loadNextAction()"></list-action>
Quel est l’intérêt de passer l'objet action complet alors que je ne me sers pas de la propriété type mais uniquement de list ? De plus je me retrouverais alors avec un objet non typé (ou alors qui serait action: { type: string, list: List} ce qui reste moins élégant que l'actuel @Input() list: List)

2022-07-26 13:55 UTC, szine commented on projects/clustaar-webchat-components/src/lib/switch/switch.html
> +    <list-action [list]="action.list" (onChoiceSelected)="choiceSelected($event)" (onLoadNextAction)="loadNextAction()"></list-action>
Parce que si un jour il y a des ajouts fait dans l'action, tu y auras pas accès, et par convention on envoie l'action entière. Exemple : Ajout d'un placeholder.

2022-07-26 14:11 UTC, Yosekai commented on projects/clustaar-webchat-components/src/lib/switch/switch.html
> +    <list-action [list]="action.list" (onChoiceSelected)="choiceSelected($event)" (onLoadNextAction)="loadNextAction()"></list-action>
Fait

2022-07-28 09:28 UTC, szine requested changes

2022-07-28 09:28 UTC, szine commented on package.json
> +    "source-map-explorer": "2.5.2",
Enlever source-map-explorer

2022-07-28 09:28 UTC, szine commented on projects/clustaar-webchat-components/src/lib/list/list.model.ts
> +}
end of line

2022-08-02 08:35 UTC, szine approved these changes

2022-10-05 08:58 UTC, szine requested changes

2022-10-05 08:58 UTC, szine commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +  @Input() inverted = false;
Le inverted est pas gerer coté html.

2022-10-05 13:24 UTC, Yosekai commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +  @Input() inverted = false;
Fait ;)

2022-10-07 07:19 UTC, szine requested changes

2022-10-07 07:19 UTC, szine commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +    console.log(this.disabled)
Enlever le console.log

2022-10-07 07:19 UTC, szine commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +    if (!this.disabled) {
disabled === false, pour éviter que ce soit disabled quand c'est null

2022-10-07 08:26 UTC, Yosekai commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +    if (!this.disabled) {
@szine  Je suis d'accord pour le console log qui ne doit pas être là, par contre sur le if je ne veux pas empêcher le fonctionnement si disabled === false mais aussi si il n'est pas défini.
De plus, avec la déclaration ( @Input() disabled? = false;) il ne peut pas être null, mais forcément false si pas défini explicitement par le composant parent.

2022-10-07 08:36 UTC, szine requested changes

2022-10-07 08:36 UTC, szine commented on projects/clustaar-webchat-components/src/lib/list/list.component.ts
> +    if (!this.disabled) {
Il peut être null, si la valeur passé en input est null.

2022-10-07 09:15 UTC, merged